Fix SetOtherUserGainForThisConnection
highfidelity/hifi-spatial-audio-unity pull request #10
Opened 2021-09-17 00:26 UTC by AndrewMeadows

- namechange all `hashedVisitId` to `visitIdHash`
- add `HiFiCommunicator.UserId` and `.VisitIdHash` properties
- add `TestHiFiCommunicator` example

2021-09-17 20:49 UTC, sabrina-shanman requested changes

2021-09-17 20:49 UTC, sabrina-shanman commented on Samples~/TestHiFiCommunicator/Scripts/TestHiFiCommunicator.cs
> +            }
This if...else clause contains the same code in both parts.

2021-09-20 15:40 UTC, AndrewMeadows commented on Runtime/HiFiCommunicator.cs
>      }
Good to know there was an old previously valid implementation.  Otherwise I had few theories as to how I could have submitted the original code as "working".

2021-09-20 15:56 UTC, AndrewMeadows commented on Samples~/TestHiFiCommunicator/Scripts/TestHiFiCommunicator.cs
> +            }
Yes.  I wanted to keep those two cases separate for debugging purposes.  I will add a log event to the first case to make it more clear why they are split.

2021-09-20 16:12 UTC, sabrina-shanman approved these changes

2021-09-20 16:27 UTC, merged